# Generated by Django 4.1.7 on 2023-04-04 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Client', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='realtimebill',
            options={'ordering': ('meterid', '-timestamp')},
        ),
        migrations.AlterUniqueTogether(
            name='billing',
            unique_together={('meterid', 'billingyear', 'billingmonth')},
        ),
    ]
