# Generated by Django 4.1.7 on 2023-03-23 10:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Client', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billinginfo',
            name='client_billinginfo',
        ),
        migrations.AlterField(
            model_name='billing',
            name='meterid',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='Client.clientinfo', verbose_name='MeterID'),
        ),
        migrations.AlterField(
            model_name='billinginfo',
            name='meterid',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='Client.clientinfo', verbose_name='MeterID'),
        ),
        migrations.AlterField(
            model_name='realtimebill',
            name='meterid',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='Client.clientinfo', verbose_name='MeterID'),
        ),
    ]
