# Generated by Django 4.1.7 on 2023-04-14 08:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Client', '0002_alter_realtimebill_options_clientinfo_isactive_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeterLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('totalconsumption', models.DecimalField(decimal_places=4, max_digits=18)),
                ('currentread', models.DecimalField(decimal_places=4, max_digits=18)),
                ('meterid', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='Client.clientinfo', verbose_name='MeterID')),
            ],
        ),
    ]
