# Generated by Django 4.1.7 on 2023-03-23 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Client', '0002_remove_billinginfo_client_billinginfo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientinfo',
            name='meterid',
            field=models.BigIntegerField(default=100000001, editable=False, unique=True),
        ),
    ]
