# Generated by Django 4.1.7 on 2023-04-14 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Client', '0003_meterlog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pricing',
            name='discountpercent',
        ),
        migrations.RemoveField(
            model_name='pricing',
            name='rate',
        ),
        migrations.AddField(
            model_name='clientinfo',
            name='isactive',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pricing',
            name='commercialrate1',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pricing',
            name='commercialrate2',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pricing',
            name='commercialrate3',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pricing',
            name='commercialrate4',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pricing',
            name='commercialrate5',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pricing',
            name='rangefrom',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pricing',
            name='rangeto',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pricing',
            name='residentalrate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
            preserve_default=False,
        ),
    ]
