# Generated by Django 4.1.7 on 2023-03-23 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Client', '0003_alter_clientinfo_meterid'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientinfo',
            name='switch',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='realtimebill',
            name='timestamp',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='realtimebill',
            unique_together={('meterid', 'timestamp')},
        ),
        migrations.RemoveField(
            model_name='realtimebill',
            name='switch',
        ),
    ]
