# Generated by Django 4.1.7 on 2023-03-23 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Client', '0004_clientinfo_switch_alter_realtimebill_timestamp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientinfo',
            name='meterid',
            field=models.BigIntegerField(default=100000001, unique=True),
        ),
    ]
