# Generated by Django 4.1.7 on 2023-04-15 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Client', '0004_remove_pricing_discountpercent_remove_pricing_rate_and_more'),
    ]

    operations = [
  
 
        migrations.AddField(
            model_name='pricing',
            name='residentialrate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
            preserve_default=False,
        ),
    ]
