# Generated by Django 4.1.7 on 2023-04-16 17:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Client', '0005_remove_pricing_discountpercent_remove_pricing_rate_and_more'),
    ]

    operations = [


        migrations.AlterField(
            model_name='pricing',
            name='commercialrate1',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
        migrations.AlterField(
            model_name='pricing',
            name='commercialrate2',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
        migrations.AlterField(
            model_name='pricing',
            name='commercialrate3',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
        migrations.AlterField(
            model_name='pricing',
            name='commercialrate4',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
        migrations.AlterField(
            model_name='pricing',
            name='commercialrate5',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
        migrations.AlterField(
            model_name='pricing',
            name='residentialrate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
        migrations.CreateModel(
            name='Notifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(default='', max_length=20)),
                ('meterid', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='Client.clientinfo', verbose_name='MeterID')),
            ],
        ),
    ]
