# Generated by Django 4.1.7 on 2023-04-17 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Client', '0006_remove_pricing_discountpercent_remove_pricing_rate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifications',
            name='timestamp',
            field=models.DateField(default=None),
        ),
    ]
