# Generated by Django 4.1.7 on 2023-04-18 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Client', '0008_remove_pricing_discountpercent_remove_pricing_rate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifications',
            name='isseen',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
