# Generated by Django 4.1.7 on 2023-04-19 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Client', '0009_notifications_isseen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notifications',
            name='timestamp',
            field=models.DateTimeField(default=None),
        ),
    ]
