# Generated by Django 4.1.7 on 2023-04-20 03:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Client', '0011_pricing_isflatrate'),
    ]

    operations = [
        migrations.AddField(
            model_name='meterlog',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 20, 11, 50, 49, 398102)),
        ),
    ]
