# Generated by Django 4.1.7 on 2023-04-20 03:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Client', '0012_meterlog_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meterlog',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 20, 3, 51, 13, 637883, tzinfo=datetime.timezone.utc)),
        ),
    ]
