# Generated by Django 4.1.7 on 2023-04-20 04:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Client', '0013_alter_meterlog_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meterlog',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 20, 4, 20, 36, 724212, tzinfo=datetime.timezone.utc)),
        ),
    ]
