# Generated by Django 4.1.7 on 2023-04-23 22:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Client', '0014_alter_meterlog_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientinfo',
            name='remarks',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='meterlog',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 23, 22, 25, 29, 268480, tzinfo=datetime.timezone.utc)),
        ),
    ]
